### PR TITLE
Update README.adoc

### PR DESCRIPTION
**Pull request by kebritam**
Fix star character by escaping

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@kebritam Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-guides/gs-validating-form-input&pullRequestId=35)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-guides/gs-validating-form-input&pullRequestId=35) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@kebritam Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-guides/gs-validating-form-input&pullRequestId=35)!

**Comment by dsyer** [comment]
It's an asciidoctor question. For me this is now rendering as 

```
th:field="*{name}" and th:field="\*{age}"
```

(So the second asterisk is showing its `\` escape prefix.) I guess that's wrong?

**Comment by Buzzardo** [comment]
I guess we need the first backslash but not the second one. Thanks, Dave.

**Comment by Buzzardo** [comment]
I noticed that we had an older PR that fixed this issue and a couple others. I have merged that one, so we can close this one. Thanks.

**Pull request closed without merging**
