### PR TITLE
Include required spring-boot-starter-validation

### LINKED ISSUE #34: Missing dependency `spring-boot-starter-validation`
The `org.springframework.boot:spring-boot-starter-validation` dependency is not mentioned in the instruction. It is not present in the _initial_ code, but it is in the _complete_ code. Following the instruction step-by-step will not produce the desired result.

- Spring Initializr. Add `Validation` to dependencies.
In the current version is:
```
This example needs the Spring Web and Thymeleaf dependencies.
```
Should be:
```
This example needs the Spring Web, Thymeleaf and Validation dependencies.
```

- Maven. Add validation library to dependencies:
```
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-validation</artifactId>
		</dependency>
```

- Gradle. Add validation library to dependencies:
```
	implementation 'org.springframework.boot:spring-boot-starter-validation'
```

- The _initial_ code should have this dependency as well.

### PR DESCRIPTION
**Pull request by mvitz**
Closes #34

### CODE REVIEW

**Comment by pivotal-issuemaster** [comment]
@mvitz Please sign the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-guides/gs-validating-form-input&pullRequestId=36)!

[Click here](https://cla.pivotal.io/sync/spring?repositoryId=spring-guides/gs-validating-form-input&pullRequestId=36) to manually synchronize the status of this Pull Request.

See the [FAQ](https://cla.pivotal.io/about) for frequently asked questions.

**Comment by pivotal-issuemaster** [comment]
@mvitz Thank you for signing the [Contributor License Agreement](https://cla.pivotal.io/sign/spring?repositoryId=spring-guides/gs-validating-form-input&pullRequestId=36)!

**Comment by mvitz** [comment]
@bclozel as you were the last one who committed could you please take a look or dispatch this MR to someone?

**Comment by bclozel** [comment]
Merged with 7b93c5f - Thanks!

**Pull request closed without merging**
